sudo: required
addons:
  apt:
    update: true

scala:
  - "2.11.11"

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      language: scala

    - os: osx
      osx_image: xcode7.3

before_install:
  - curl -O https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh
  - chmod +x travis_setup.sh
  - bash travis_setup.sh

before_script:
  - sudo chmod +x /usr/local/bin/sbt
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] ; then
      echo "Incoming pull request from https://github.com/$TRAVIS_REPO_SLUG/pull/$TRAVIS_PULL_REQUEST";
      author=$(curl -u dummy4dummy:dummy2dummy -s "https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST" | jq -r ".user.login");
      if [ $? -ne 0 ] ; then exit 1; fi;
      echo "Pull request submitted by $author";
      signed=$(curl -s https://www.lightbend.com/contribute/cla/scala/check/$author | jq -r ".signed");
      if [ $? -ne 0 ] ; then exit 1; fi;
      if [ "$signed" = "true" ] ; then
        echo "CLA check for $author successful";
      else
        echo "CLA check for $author failed";
        echo "Please sign the Scala CLA to contribute to sbt-crossproject";
        echo "Go to https://www.lightbend.com/contribute/cla/scala and then resubmit this pull request";
        exit 1;
      fi;
    fi;

script:
  - java -version
  - scripts/scalafmt --test
  - sbt sbt-crossproject-test/scripted
  - sbt ++2.10.7 ^^0.13.17 sbt-crossproject-test/scripted

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
